server.port=9000

server.servlet.context-path=

springdoc.swagger-ui.path=/

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:file:./file/demoDB;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

hibernate.globally_quoted_identifiers=true
hibernate.jadira.usertype.autoRegisterUserTypes=true
hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy
hibernate.show_sql=true
hibernate.use_sql_comments=false
hibernate.format_sql=true
hibernate.generate_statistics=true
hibernate.jdbc.time_zone=Asia/Taipei
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.template.confirm-timeout=10000ms
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=5